apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  POSTGRES_DB: "todos"
  POSTGRES_USER: "todos"
  POSTGRES_PASSWORD: "password"
  PGHOST: "todo-db-svc"
  PGPORT: "5432"
  PGDATABASE: "todos"
  PGUSER: "todos"
  PORT: "3001"
  HOST: "todo-backend-svc"
  TODO_SERVICE_PORT: "80"