apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-creator
  namespace: project
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-creator
              image: lindkon/todo-backend:2.9i
              command: ["node", "src/addWikiTodo.js"]
              envFrom:
                - configMapRef:
                    name: todo-backend-config
          restartPolicy: OnFailure