apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  namespace: project
spec:
  serviceName: todo-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: todo-backend-config
          volumeMounts:
            - name: todo-storage
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: todo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi