apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  ### IMPORTANT ###
  # Secrets are not in kustomize, must be deployed manually when changed.

resources:
  - ../manifests
  - ../todo-app/manifests
  - ../todo-backend/manifests
  - ../broadcaster/manifests
images:
- name: lindkon/broadcaster
  newName: lindkon/broadcaster
  newTag: 1685885173631edf1d2c48c43643b194553e9b61
- name: lindkon/get-image
  newName: lindkon/get-image
  newTag: 1685885173631edf1d2c48c43643b194553e9b61
- name: lindkon/todo-backend
  newName: lindkon/todo-backend
  newTag: 1685885173631edf1d2c48c43643b194553e9b61
- name: lindkon/todo-main
  newName: lindkon/todo-main
  newTag: 1685885173631edf1d2c48c43643b194553e9b61
