apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  ### IMPORTANT ###
  # Secrets are not in kustomize, must be deployed manually when changed.

resources:
- ../manifests
- ../todo-app/manifests
- ../todo-backend/manifests
- ../broadcaster/manifests
images:
- name: lindkon/broadcaster
  newName: lindkon/broadcaster
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/get-image
  newName: lindkon/get-image
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/todo-backend
  newName: lindkon/todo-backend
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/todo-main
  newName: lindkon/todo-main
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
