apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ../../base
- backup.yaml
- backup-pvc.yaml
- route.yaml

images:
- name: lindkon/broadcaster
  newTag: a12d55c98d81d8cb8397e92afe9740ef87a3b8a5
- name: lindkon/get-image
  newTag: a12d55c98d81d8cb8397e92afe9740ef87a3b8a5
- name: lindkon/todo-backend
  newTag: a12d55c98d81d8cb8397e92afe9740ef87a3b8a5
- name: lindkon/todo-main
  newTag: a12d55c98d81d8cb8397e92afe9740ef87a3b8a5
