apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
  - ../../base
  - backup.yaml
  - backup-pvc.yaml
  - route.yaml

images:
- name: lindkon/broadcaster
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/get-image
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/todo-backend
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
- name: lindkon/todo-main
  newTag: de963f05892a1116ac8af6409ab77cb46f37f77e
