apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: todo-app
          image: lindkon/todo-app:1.13b
          env:
          - name: PORT
            value: "3001"
          volumeMounts:
          - name: image-storage
            mountPath: /usr/src/app/files
        - name: get-image
          image: lindkon/get-image:1.12f
          env:
          - name: PORT
            value: "3000"
          volumeMounts:
          - name: image-storage
            mountPath: /usr/src/app/files