apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-pong-config
  namespace: exercises
data:
  POSTGRES_DB: "pingpong"
  POSTGRES_USER: "pingpong"
  POSTGRES_PASSWORD: "password"
  PGHOST: "ping-pong-db-svc"
  PGPORT: "5432"
  PGDATABASE: "pingpong"
  PGUSER: "pingpong"
  PORT: "3001"