apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
  # infra
  # ping-pong
  # logging
resources:
- manifests/gateway.yaml
- manifests/persistentvolume.yaml
- manifests/persistentVolumeClaim.yaml
- manifests/route.yaml
- ping-pong/manifests/analysis-template.yaml
- ping-pong/manifests/configmap.yaml
- ping-pong/manifests/headless-service.yaml
- ping-pong/manifests/rollout.yaml
- ping-pong/manifests/service.yaml
- ping-pong/manifests/statefulset.yaml
- log/manifests/deployment.yaml
- log/manifests/service.yaml
images:
- name: lindkon/log-read
  newName: lindkon/log-read
  newTag: 0f87b7ce477d833c9f9b8440ed2a7a92a30f4baf
- name: lindkon/log-write
  newName: lindkon/log-write
  newTag: 0f87b7ce477d833c9f9b8440ed2a7a92a30f4baf
- name: lindkon/ping-pong
  newName: lindkon/ping-pong
  newTag: 0f87b7ce477d833c9f9b8440ed2a7a92a30f4baf
