apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
  # infra
  # ping-pong
  # logging
resources:
- manifests/persistentvolume.yaml
- manifests/persistentVolumeClaim.yaml
- manifests/route.yaml
- ping-pong/manifests/analysis-template.yaml
- ping-pong/manifests/configmap.yaml
- ping-pong/manifests/headless-service.yaml
- ping-pong/manifests/rollout.yaml
- ping-pong/manifests/service.yaml
- ping-pong/manifests/statefulset.yaml
- log/manifests/deployment.yaml
- log/manifests/service.yaml
images:
- name: lindkon/log-read
  newName: lindkon/log-read
  newTag: d7fec1b5a9802b939fc9085832a8b84f1c69f820
- name: lindkon/log-write
  newName: lindkon/log-write
  newTag: d7fec1b5a9802b939fc9085832a8b84f1c69f820
- name: lindkon/ping-pong
  newName: lindkon/ping-pong
  newTag: d7fec1b5a9802b939fc9085832a8b84f1c69f820
